### ISSUE TITLE
Is this plugin still useful in Matomo v4?

### ISSUE THREAD

**Issue by Berbe** [nodeone/userconsole#4]
If this plugin is still useful with Matomo v4, [documentation](https://developer.matomo.org/guides/migrate-matomo-3-to-4) is available on how to make it compatible.

**Comment by chriscroome** [comment]
I'd like to continue to use this plugin if it is supported and seeing as [the latest release](https://github.com/matomo-org/matomo/releases) is now 4.0.0-rc6 the first production version of Matomo v4 might be imminent?

With 4.0.0-rc6 you get this:

```bash
php console --no-ansi -n plugin:activate UserConsole
  UserConsole requires Piwik <4.0.0-b1.
```

**Comment by mikkeschiren** [comment]
Hi,

Yes this will be fixed.

/mikke

**Comment by mikkeschiren** [comment]
I have pushed now a first version for 4.x - 4.0.0. I should maybe have marked it as a beta, because it not properly tested yet. But it is out any how :-)
